#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsSqlExTsFields() works", {

  expect_error(
    kwb.db:::hsSqlExTsFields()
    # argument "tsField" is missing, with no default
  )

})

