#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("sqlLeftJoinBody() works", {

  expect_error(
    kwb.db:::sqlLeftJoinBody()
    # argument "leftSql" is missing, with no default
  )

})

