#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".toCondition() works", {

  expect_error(
    kwb.db:::.toCondition()
    # argument "value" is missing, with no default
  )

})

