#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".argumentsToSqlExpressions() works", {

  expect_error(
    kwb.db:::.argumentsToSqlExpressions()
    # argument "FUN" is missing, with no default
  )

})

