#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".message_availableTables() works", {

  expect_error(
    kwb.db:::.message_availableTables()
    # argument "tableNames" is missing, with no default
  )

})

