#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("setCurrentSqlDialect() works", {

  expect_error(
    kwb.db:::setCurrentSqlDialect()
    # argument "dialectName" is missing, with no default
  )

})

