#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("renamesToFieldList() works", {

  expect_error(
    kwb.db:::renamesToFieldList()
    # argument "renames" is missing, with no default
  )

})

