#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".hsJetType() works", {

  expect_error(
    kwb.db:::.hsJetType()
    # argument "rtype" is missing, with no default
  )

})

