#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("keyValuesToSqlAssignment2() works", {

  expect_error(
    kwb.db:::keyValuesToSqlAssignment2()
    # argument "keyvalues" is missing, with no default
  )

})

