#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("selectFromTable() works", {

  expect_error(
    kwb.db:::selectFromTable()
    # argument "arguments" is missing, with no default
  )

})

