#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".tableNameToFunctionName() works", {

  expect_error(
    kwb.db:::.tableNameToFunctionName()
    # argument "tableName" is missing, with no default
  )

})

