#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("sqlForInsertDataFrame() works", {

  expect_error(
    kwb.db:::sqlForInsertDataFrame()
    # argument "tablename" is missing, with no default
  )

})

