#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsCloseMdb() works", {

  expect_error(
    kwb.db:::hsCloseMdb()
    # argument "con" is missing, with no default
  )

})

