#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsLookupOrAddRecord() works", {

  expect_error(
    kwb.db:::hsLookupOrAddRecord()
    # argument "keyAssigns" is missing, with no default
  )

})

