#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".sqlForeignKey() works", {

  expect_error(
    kwb.db:::.sqlForeignKey()
    # argument "tbl" is missing, with no default
  )

})

