#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("sqlForInsertFromSelect() works", {

  expect_error(
    kwb.db:::sqlForInsertFromSelect()
    # argument "fields" is missing, with no default
  )

})

