#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getTable() works", {

  expect_error(
    kwb.db:::.getTable()
    # argument "x" is missing, with no default
  )

})

