#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".horizontalLine() works", {

  expect_error(
    kwb.db:::.horizontalLine()
    # argument "functionName" is missing, with no default
  )

})

