#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("safeTableName() works", {

  expect_error(
    kwb.db:::safeTableName()
    # argument "tableName" is missing, with no default
  )

})

