#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getFieldSchema() works", {

  expect_error(
    kwb.db:::.getFieldSchema()
    # argument "sqlDialect" is missing, with no default
  )

})

