#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("isAccessFile() works", {

  expect_error(
    kwb.db:::isAccessFile()
    # argument "filepath" is missing, with no default
  )

})

