#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("keyValueToSql() works", {

  expect_error(
    kwb.db:::keyValueToSql()
    # argument "cvalue" is missing, with no default
  )

})

