#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".sqlEquals() works", {

  expect_error(
    kwb.db:::.sqlEquals()
    # argument "leftSide" is missing, with no default
  )

})

