#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("runSqlCommandsFromFile() works", {

  expect_error(
    kwb.db:::runSqlCommandsFromFile()
    # argument "sqlFile" is missing, with no default
  )

})

