#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("sqlLeftJoin() works", {

  expect_error(
    kwb.db:::sqlLeftJoin()
    # argument "tablesAndIDs" is missing, with no default
  )

})

