#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("keyValuesToSqlAssignment() works", {

  expect_error(
    kwb.db:::keyValuesToSqlAssignment()
    # argument "keyValues" is missing, with no default
  )

})

