#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("isAccess2007File() works", {

  expect_error(
    kwb.db:::isAccess2007File()
    # argument "filepath" is missing, with no default
  )

})

