#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".toSafeIndices() works", {

  expect_error(
    kwb.db:::.toSafeIndices()
    # non-numeric argument to mathematical function
  )

})

