#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("rcode_tableAccess() works", {

  expect_error(
    kwb.db:::rcode_tableAccess()
    # argument "tableSchema" is missing, with no default
  )

})

