#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("currentDb() works", {

  expect_error(
    kwb.db:::currentDb()
    # Please specify the database or use 'setCurrentDb' to set the current database!
  )

})

