#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsJetDate() works", {

  expect_error(
    kwb.db:::hsJetDate()
    # argument "datetime" is missing, with no default
  )

})

