#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("sqlLeftJoinExpression() works", {

  expect_error(
    kwb.db:::sqlLeftJoinExpression()
    # argument "left" is missing, with no default
  )

})

