#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("sqlForUpdate() works", {

  expect_error(
    kwb.db:::sqlForUpdate()
    # argument "tablename" is missing, with no default
  )

})

