#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".hsMySqlType() works", {

  expect_error(
    kwb.db:::.hsMySqlType()
    # argument "rtype" is missing, with no default
  )

})

