#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("readSqlCommandsFromFile() works", {

  expect_error(
    kwb.db:::readSqlCommandsFromFile()
    # argument "sqlScript" is missing, with no default
  )

})

