#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".callWithMessages() works", {

  expect_error(
    kwb.db:::.callWithMessages()
    # argument "dbg" is missing, with no default
  )

})

