#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsClearTable() works", {

  expect_error(
    kwb.db:::hsClearTable()
    # argument "tbl" is missing, with no default
  )

})

