#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getAlias() works", {

  expect_error(
    kwb.db:::.getAlias()
    # argument "x" is missing, with no default
  )

})

