#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".namesAndValuesToConditions() works", {

  expect_error(
    kwb.db:::.namesAndValuesToConditions()
    # argument "values" is missing, with no default
  )

})

