#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getTableNamesMatchingPattern() works", {

  expect_error(
    kwb.db:::.getTableNamesMatchingPattern()
    # argument "tableSchemata" is missing, with no default
  )

})

