#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("sqlForSelectByKey() works", {

  expect_error(
    kwb.db:::sqlForSelectByKey()
    # argument "tablename" is missing, with no default
  )

})

