#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("odbcConnectionExcel() works", {

  expect_error(
    kwb.db:::odbcConnectionExcel()
    # argument "db" is missing, with no default
  )

})

