#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("lookupRecord() works", {

  expect_error(
    kwb.db:::lookupRecord()
    # argument "keyAssignments" is missing, with no default
  )

})

