#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".getTableSchemata() works", {

  expect_error(
    kwb.db:::.getTableSchemata()
    # argument "dbSchema" is missing, with no default
  )

})

