#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("dataFrameToSqlTuples() works", {

  expect_error(
    kwb.db:::dataFrameToSqlTuples()
    # argument "newData" is missing, with no default
  )

})

