#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("sqlForInsert() works", {

  expect_error(
    kwb.db:::sqlForInsert()
    # argument "sqlSource" is missing, with no default
  )

})

