#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsSqlExTimeGroup() works", {

  expect_error(
    kwb.db:::hsSqlExTimeGroup()
    # argument "interval" is missing, with no default
  )

})

