#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("sqlDateExpression() works", {

  expect_error(
    kwb.db:::sqlDateExpression()
    # argument "sqlDialect" is missing, with no default
  )

})

