#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("listValuesToSql() works", {

  expect_error(
    kwb.db:::listValuesToSql()
    # argument "x" is missing, with no default
  )

})

