#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("printDatabaseSchema() works", {

  expect_error(
    kwb.db:::printDatabaseSchema()
    # argument "dbSchema" is missing, with no default
  )

})

