#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("argumentsToSqlParts() works", {

  expect_error(
    kwb.db:::argumentsToSqlParts()
    # argument "selects" is missing, with no default
  )

})

