#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".argumentsToConditions() works", {

  expect_error(
    kwb.db:::.argumentsToConditions()
    # argument "arguments" is missing, with no default
  )

})

