#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsDumpMdb() works", {

  expect_error(
    kwb.db:::hsDumpMdb()
    # argument "mdb" is missing, with no default
  )

})

