#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".argumentsToFieldNames() works", {

  expect_error(
    kwb.db:::.argumentsToFieldNames()
    # argument "arguments" is missing, with no default
  )

})

