#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".addClauseIfGiven() works", {

  expect_error(
    kwb.db:::.addClauseIfGiven()
    # argument "clause" is missing, with no default
  )

})

